/*
 * File: app/view/KeyboardFittsLaw.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.KeyboardFittsLaw', {
    extend: 'Ext.Panel',
    alias: 'widget.KeyboardFittsLaw',

    config: {
        margin: 5,
        ui: '',
        layout: {
            align: 'center',
            pack: 'center',
            type: 'hbox'
        },
        items: [
            {
                xtype: 'panel',
                flex: 1,
                items: [
                    {
                        xtype: 'panel',
                        layout: {
                            align: 'start',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'mybutton',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 50,
                                text: '1'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton1',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 50,
                                text: '2'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton2',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 50,
                                text: '3'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton3',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 50,
                                text: '4'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton4',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 50,
                                text: '5'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton5',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 50,
                                text: '6'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        layout: {
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'mybutton6',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 35,
                                text: 'Q'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton7',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 50,
                                text: 'W'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton8',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 63,
                                text: 'E'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton9',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 50,
                                text: 'R'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton10',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 63,
                                text: 'T'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        layout: {
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'mybutton11',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 63,
                                text: 'A'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton12',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 63,
                                text: 'S'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton13',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 50,
                                text: 'D'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton14',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 50,
                                text: 'F'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton32',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 35,
                                text: 'G'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        layout: {
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 63,
                                text: 'sh'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton16',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 35,
                                text: 'Z'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton17',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 35,
                                text: 'X'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton18',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 50,
                                text: 'C'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton19',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 35,
                                text: 'V'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        layout: {
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'mybutton21',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 320,
                                text: ''
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                flex: 1,
                items: [
                    {
                        xtype: 'textfield',
                        id: 'outputfield',
                        itemId: '',
                        label: '',
                        name: 'outputfield',
                        readOnly: true
                    }
                ]
            },
            {
                xtype: 'panel',
                flex: 1,
                items: [
                    {
                        xtype: 'panel',
                        layout: {
                            align: 'end',
                            pack: 'end',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'mybutton22',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 50,
                                text: '7'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton23',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 50,
                                text: '8'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton24',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 50,
                                text: '9'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton25',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 50,
                                text: '0'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton26',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 63,
                                text: 'bac'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        layout: {
                            align: 'end',
                            pack: 'end',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'mybutton27',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 35,
                                text: 'Y'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton28',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 50,
                                text: 'U'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton29',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 63,
                                text: 'I'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton30',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 63,
                                text: 'O'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton31',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 35,
                                text: 'P'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        layout: {
                            align: 'end',
                            pack: 'end',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'mybutton33',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 63,
                                text: 'H'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton34',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 35,
                                text: 'J'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton35',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 35,
                                text: 'K'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton36',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 50,
                                text: 'L'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        layout: {
                            align: 'end',
                            pack: 'end',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'mybutton37',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 35,
                                text: 'B'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton38',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 63,
                                text: 'N'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton39',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 50,
                                text: 'M'
                            },
                            {
                                xtype: 'button',
                                itemId: 'mybutton40',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 63,
                                text: 'sh'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        layout: {
                            align: 'end',
                            pack: 'end',
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'mybutton41',
                                margin: 2,
                                minHeight: 39,
                                minWidth: 300,
                                text: ''
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMybuttonTap',
                event: 'tap',
                delegate: '#mybutton'
            },
            {
                fn: 'onMybutton1Tap',
                event: 'tap',
                delegate: '#mybutton1'
            },
            {
                fn: 'onMybutton2Tap',
                event: 'tap',
                delegate: '#mybutton2'
            },
            {
                fn: 'onMybutton3Tap',
                event: 'tap',
                delegate: '#mybutton3'
            },
            {
                fn: 'onMybutton4Tap',
                event: 'tap',
                delegate: '#mybutton4'
            },
            {
                fn: 'onMybutton5Tap',
                event: 'tap',
                delegate: '#mybutton5'
            },
            {
                fn: 'onMybutton6Tap',
                event: 'tap',
                delegate: '#mybutton6'
            },
            {
                fn: 'onMybutton7Tap',
                event: 'tap',
                delegate: '#mybutton7'
            },
            {
                fn: 'onMybutton8Tap',
                event: 'tap',
                delegate: '#mybutton8'
            },
            {
                fn: 'onMybutton9Tap',
                event: 'tap',
                delegate: '#mybutton9'
            },
            {
                fn: 'onMybutton10Tap',
                event: 'tap',
                delegate: '#mybutton10'
            },
            {
                fn: 'onMybutton11Tap',
                event: 'tap',
                delegate: '#mybutton11'
            },
            {
                fn: 'onMybutton12Tap',
                event: 'tap',
                delegate: '#mybutton12'
            },
            {
                fn: 'onMybutton13Tap',
                event: 'tap',
                delegate: '#mybutton13'
            },
            {
                fn: 'onMybutton14Tap',
                event: 'tap',
                delegate: '#mybutton14'
            },
            {
                fn: 'onMybutton32Tap',
                event: 'tap',
                delegate: '#mybutton32'
            },
            {
                fn: 'onMybutton16Tap',
                event: 'tap',
                delegate: '#mybutton16'
            },
            {
                fn: 'onMybutton17Tap',
                event: 'tap',
                delegate: '#mybutton17'
            },
            {
                fn: 'onMybutton18Tap',
                event: 'tap',
                delegate: '#mybutton18'
            },
            {
                fn: 'onMybutton19Tap',
                event: 'tap',
                delegate: '#mybutton19'
            },
            {
                fn: 'onMybutton21Tap',
                event: 'tap',
                delegate: '#mybutton21'
            },
            {
                fn: 'onMybutton23Tap',
                event: 'tap',
                delegate: '#mybutton23'
            },
            {
                fn: 'onMybutton24Tap',
                event: 'tap',
                delegate: '#mybutton24'
            },
            {
                fn: 'onMybutton25Tap',
                event: 'tap',
                delegate: '#mybutton25'
            },
            {
                fn: 'onMybutton26Tap',
                event: 'tap',
                delegate: '#mybutton26'
            },
            {
                fn: 'onMybutton27Tap',
                event: 'tap',
                delegate: '#mybutton27'
            },
            {
                fn: 'onMybutton28Tap',
                event: 'tap',
                delegate: '#mybutton28'
            },
            {
                fn: 'onMybutton29Tap',
                event: 'tap',
                delegate: '#mybutton29'
            },
            {
                fn: 'onMybutton30Tap',
                event: 'tap',
                delegate: '#mybutton30'
            },
            {
                fn: 'onMybutton31Tap',
                event: 'tap',
                delegate: '#mybutton31'
            },
            {
                fn: 'onMybutton33Tap',
                event: 'tap',
                delegate: '#mybutton33'
            },
            {
                fn: 'onMybutton34Tap',
                event: 'tap',
                delegate: '#mybutton34'
            },
            {
                fn: 'onMybutton35Tap',
                event: 'tap',
                delegate: '#mybutton35'
            },
            {
                fn: 'onMybutton36Tap',
                event: 'tap',
                delegate: '#mybutton36'
            },
            {
                fn: 'onMybutton37Tap',
                event: 'tap',
                delegate: '#mybutton37'
            },
            {
                fn: 'onMybutton38Tap',
                event: 'tap',
                delegate: '#mybutton38'
            },
            {
                fn: 'onMybutton39Tap',
                event: 'tap',
                delegate: '#mybutton39'
            },
            {
                fn: 'onMybutton40Tap',
                event: 'tap',
                delegate: '#mybutton40'
            },
            {
                fn: 'onMybutton41Tap',
                event: 'tap',
                delegate: '#mybutton41'
            }
        ]
    },

    onMybuttonTap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"1");
    },

    onMybutton1Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"2");
    },

    onMybutton2Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"3");
    },

    onMybutton3Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"4");
    },

    onMybutton4Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"5");
    },

    onMybutton5Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"6");
    },

    onMybutton6Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"Q");
    },

    onMybutton7Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"W");
    },

    onMybutton8Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"E");
    },

    onMybutton9Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"R");
    },

    onMybutton10Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"T");
    },

    onMybutton11Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"A");
    },

    onMybutton12Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"S");
    },

    onMybutton13Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"D");
    },

    onMybutton14Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"F");
    },

    onMybutton32Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"G");
    },

    onMybutton16Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"Z");
    },

    onMybutton17Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"X");
    },

    onMybutton18Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"C");
    },

    onMybutton19Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"V");
    },

    onMybutton21Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        var outputarea = Ext.getCmp("outputarea");
        outputarea.setValue(outputarea.getValue() + " " + outputfield.getValue());
        outputfield.setValue("");
    },

    onMybutton23Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"8");
    },

    onMybutton24Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"9");
    },

    onMybutton25Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"0");
    },

    onMybutton26Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue().substring(0,outputfield.getValue().length-1));
    },

    onMybutton27Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"Y");
    },

    onMybutton28Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"U");
    },

    onMybutton29Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"I");
    },

    onMybutton30Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"O");
    },

    onMybutton31Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"P");
    },

    onMybutton33Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"H");
    },

    onMybutton34Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"J");
    },

    onMybutton35Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"K");
    },

    onMybutton36Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"L");
    },

    onMybutton37Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"B");
    },

    onMybutton38Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"N");
    },

    onMybutton39Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        outputfield.setValue(outputfield.getValue()+"M");
    },

    onMybutton40Tap: function(button, e, options) {

    },

    onMybutton41Tap: function(button, e, options) {
        var outputfield = Ext.getCmp("outputfield");
        var outputarea = Ext.getCmp("outputarea");
        outputarea.setValue(outputarea.getValue() + " " + outputfield.getValue());
        outputfield.setValue("");
    }

});