/*
 * File: app/view/RootPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.RootPanel', {
    extend: 'Ext.Panel',

    config: {
        items: [
            {
                xtype: 'button',
                itemId: 'mybutton21',
                text: 'MyButton21'
            }
        ],
        listeners: [
            {
                fn: 'onMybutton21Tap',
                event: 'tap',
                delegate: '#mybutton21'
            }
        ]
    },

    onMybutton21Tap: function(button, e, options) {
        this.hide();
        TestPanel.show();
        TestPanel.start();
    }

});