/*
 * File: app/view/TestPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.TestPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.testpanel',

    config: {
        id: 'testPanel',
        layout: {
            type: 'vbox'
        },
        items: [
            {
                xtype: 'panel',
                flex: 1,
                itemId: 'textPanel',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'textareafield',
                        id: 'outputPanel',
                        itemId: 'outputPanel',
                        style: 'text-align:center',
                        label: '',
                        readOnly: true
                    }
                ]
            },
            {
                xtype: 'panel',
                itemId: 'emptyKeyboard'
            }
        ]
    },

    getNextPhrase: function() {
        var phrases = [
        "my watch fell in the water",
        "prevailing wind from the east",
        "never too rich and never too thin",
        "breathing is difficult",
        "I can see the rings on Saturn",
        "physics and chemistry are hard",
        "my bank account is overdrawn",
        "elections bring out the best",
        "we are having spaghetti",
        "time to go shopping",
        "a problem with the engine",
        "elephants are afraid of mice",
        "my favorite place to visit",
        "three two one zero blast off",
        "my favorite subject is psychology",
        "circumstances are unacceptable",
        "watch out for low flying objects",
        "if at first you do not succeed",
        "please provide your date of birth",
        "we run the risk of failure",
        "prayer in schools offends some",
        "he is just like everyone else",
        "great disturbance in the force",
        "love means many things",
        "you must be getting old",
        "the world is a stage",
        "can I skate with sister today",
        "neither a borrower nor a lender be",
        "one heck of a question",
        "question that must be answered",
        "beware the ides of March",
        "double double toil and trouble",
        "the power of denial",
        "I agree with you",
        "do not say anything",
        "play it again Sam",
        "the force is with you",
        "you are not a jedi yet",
        "an offer you cannot refuse",
        "are you talking to me",
        "yes you are very smart",
        "all work and no play",
        "hair gel is very greasy",
        "Valium in the economy size",
        "the facts get in the way",
        "the dreamers of dreams",
        "did you have a good time",
        "space is a high priority",
        "you are a wonderful example",
        "do not squander your time",
        "do not drink too much",
        "take a coffee break",
        "popularity is desired by all",
        "the music is better than it sounds",
        "starlight and dewdrop",
        "the living is easy",
        "fish are jumping",
        "the cotton is high",
        "drove my chevy to the levee",
        "but the levee was dry",
        "I took the rover from the shop",
        "movie about a nutty professor",
        "come and see our new car",
        "coming up with killer sound bites",
        "I am going to a music lesson",
        "the opposing team is over there",
        "soon we will return from the city",
        "I am wearing a tie and a jacket",
        "the quick brown fox jumped",
        "all together in one big pile",
        "wear a crown with many jewels",
        "there will be some fog tonight",
        "I am allergic to bees and peanuts",
        "he is still on our team",
        "the dow jones index has risen",
        "my preferred treat is chocolate",
        "the king sends you to the tower",
        "we are subjects and must obey",
        "mom made her a turtleneck",
        "goldilocks and the three bears",
        "we went grocery shopping",
        "the assignment is due today",
        "what you see is what you get",
        "for your information only",
        "a quarter of a century",
        "the store will close at ten",
        "head shoulders knees and toes",
        "vanilla flavored ice cream",
        "frequently asked questions",
        "round robin scheduling",
        "information super highway",
        "my favorite web browser",
        "the laser printer is jammed",
        "all good boys deserve fudge",
        "the second largest country",
        "call for more details",
        "just in time for the party",
        "have a good weekend",
        "video camera with a zoom lens",
        "what a monkey sees a monkey will do"
        ];

        var randomIndex = 1+100*(Math.random());
        randomIndex = Math.round(randomIndex);
        return phrases[randomIndex];
    },

    setKeyboard: function(keyboard) {
        this.removeAt(this.getItems().length-1);
        this.add(keyboard);
    },

    counter: function(word) {
        // ToDo: ist word an aktueller Stelle richtig?
        // ToDo: abhängig davon rot oder grün einfärben.
        var phrase1 = this.phrase1.replace(/<\/?[^>]+(>|$)/g, "");
        var words = phrase1.split(" ");
        var phraseWord = words[this.currentWord];
        // Prüfen word == phraseWord

        var errorCounter = 0;
        for(var i = 0; i < word.length; i++){
            typedCharacter = word.charAt(i);
            if(phraseWord.length > i){
                // Prüfe, ob aktueller Buchstabe korrekt ist
                var givenCharacter = phraseWord.charAt(i);
                if(typedCharacter != givenCharacter){
                    errorCounter++;
                }
            }else{
                // typedWord zu kurz, restlichen Buchstaben als Fehler
                errorCounter++;
            }
        }
        // wenn zu kurz, Rest fehler
        if(i < phraseWord.length){
            errorCounter = errorCounter + (phraseWord.length -i);
        }

        // markiere aktuelles Wort grün oder rot
        var phraseWordHtml = "";
        if(errorCounter == 0){
            // grün
            phraseWordHtml = "<span style=\"color: green;\">" + phraseWord + "</span>";
        }else{
            // rot
            phraseWordHtml = "<span style=\"color: red;\">" + phraseWord + "</span>";
        }

        // Zähle Buckstaben: vom wort gesamt, falsche buchstaben
        this.characterCounter += word.length;
        this.characterErrorCounter += errorCounter;

        // erzeuge this.phrase1 aus Teilen
        this.phrase1 = this.phrase1.replace(new RegExp(phraseWord,"i"), phraseWordHtml);

        this.currentWord++;
        if(this.currentWord >= words.length){
            this.phrase1 = this.phrase2;
            this.phrase2 = this.getNextPhrase();
            this.currentWord = 0;

        }

        // Print outputArea
        var output = this.phrase1 + "<br/><br/>" + this.phrase2;
        this.getComponent("textPanel").getComponent("outputPanel").setHtml(output);

    },

    startTest: function() {
        // hole ZWEI Phrases
        this.phrase1 = this.getNextPhrase();
        this.phrase2 = this.getNextPhrase();

        this.currentWord = 0;
        this.currentChar = 0;
        // ToDo: Print in outputPanel

        var output = this.phrase1 + "<br/><br/>" + this.phrase2;
        this.getComponent("textPanel").getComponent("outputPanel").setHtml(output);

        if(Ext.getCmp("outputfield")) {
            Ext.getCmp("outputfield").setValue("");
            Ext.getCmp("outputfield").setStyle("background-color: transparent;");
        }

        this.characterCounter = 0;
        this.characterErrorCounter = 0;
    },

    check: function(word) {
        var phrase1 = this.phrase1.replace(/<\/?[^>]+(>|$)/g, "");
        var words = phrase1.split(" ");
        var phraseWord = words[this.currentWord];

        var iscorrect = phraseWord.indexOf(word) == 0;

        return iscorrect;
    }

});